# WARNING: this file was autogenerated by generate-browser-image.js
# using
#   yarn add:browser -- 16.18.1 --chrome=108 --firefox=107 --edge
set e+x

LOCAL_NAME=cypress/browsers:node16.18.1-chrome-ff-edge
echo "Building $LOCAL_NAME"
docker build -t $LOCAL_NAME .
